SiteTree:
  extensions:
    - SiteTreeContentReview
Group:
  extensions:
    - ContentReviewOwner
Member:
  extensions:
    - ContentReviewOwner
CMSPageEditController:
  extensions:
    - ContentReviewCMSPageEditController